# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Anasayfa.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1884, 954)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setStatusTip("")
        MainWindow.setStyleSheet("\n"
"QMainWindow {\n"
"    background-color:#ececec;\n"
"}\n"
"QPushButton, QToolButton, QCommandLinkButton{\n"
"    padding: 0 5px 0 5px;\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-right-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-width: 2px;\n"
"    border-radius: 8px;\n"
"    color: #616161;\n"
"    font-weight: bold;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #fbfdfd, stop:0.5 #ffffff, stop:1 #fbfdfd);\n"
"}\n"
"QPushButton::default, QToolButton::default, QCommandLinkButton::default{\n"
"    border: 2px solid transparent;\n"
"    color: #FFFFFF;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #84afe5, stop:1 #1168e4);\n"
"}\n"
"QPushButton:hover, QToolButton:hover, QCommandLinkButton:hover{\n"
"    color: #3d3d3d;\n"
"}\n"
"QPushButton:pressed, QToolButton:pressed, QCommandLinkButton:pressed{\n"
"    color: #aeaeae;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #ffffff, stop:0.5 #fbfdfd, stop:1 #ffffff);\n"
"}\n"
"QPushButton:disabled, QToolButton:disabled, QCommandLinkButton:disabled{\n"
"    color: #616161;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #dce7eb, stop:0.5 #e0e8eb, stop:1 #dee7ec);\n"
"}\n"
"QLineEdit, QTextEdit, QPlainTextEdit, QSpinBox, QDoubleSpinBox, QTimeEdit, QDateEdit, QDateTimeEdit {\n"
"    border-width: 2px;\n"
"    border-radius: 8px;\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    background-color: #f4f4f4;\n"
"    color: #3d3d3d;\n"
"}\n"
"QLineEdit:focus, QTextEdit:focus, QPlainTextEdit:focus, QSpinBox:focus, QDoubleSpinBox:focus, QTimeEdit:focus, QDateEdit:focus, QDateTimeEdit:focus {\n"
"    border-width: 2px;\n"
"    border-radius: 8px;\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"    border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"    background-color: #f4f4f4;\n"
"    color: #3d3d3d;\n"
"}\n"
"QLineEdit:disabled, QTextEdit:disabled, QPlainTextEdit:disabled, QSpinBox:disabled, QDoubleSpinBox:disabled, QTimeEdit:disabled, QDateEdit:disabled, QDateTimeEdit:disabled {\n"
"    color: #b9b9b9;\n"
"}\n"
"QSpinBox::up-button, QDoubleSpinBox::up-button, QTimeEdit::up-button, QDateEdit::up-button, QDateTimeEdit::up-button {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    color: #272727;\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    padding: 3px;\n"
"}\n"
"QSpinBox::down-button, QDoubleSpinBox::down-button, QTimeEdit::down-button, QDateEdit::down-button, QDateTimeEdit::down-button {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: bottom right;\n"
"    width: 15px;\n"
"    color: #272727;\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-bottom-right-radius: 3px;\n"
"    padding: 3px;\n"
"}\n"
"QSpinBox::up-button:pressed, QDoubleSpinBox::up-button:pressed, QTimeEdit::up-button:pressed, QDateEdit::up-button:pressed, QDateTimeEdit::up-button:pressed {\n"
"    color: #aeaeae;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #ffffff, stop:0.5 #fbfdfd, stop:1 #ffffff);\n"
"}\n"
"QSpinBox::down-button:pressed, QDoubleSpinBox::down-button:pressed, QTimeEdit::down-button:pressed, QDateEdit::down-button:pressed, QDateTimeEdit::down-button:pressed {\n"
"    color: #aeaeae;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #ffffff, stop:0.5 #fbfdfd, stop:1 #ffffff);\n"
"}\n"
"QSpinBox::up-button:hover, QDoubleSpinBox::up-button:hover, QTimeEdit::up-button:hover, QDateEdit::up-button:hover, QDateTimeEdit::up-button:hover {\n"
"    color: #FFFFFF;\n"
"    border-top-right-radius: 5px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #84afe5, stop:1 #1168e4);\n"
"    \n"
"}\n"
"QSpinBox::down-button:hover, QDoubleSpinBox::down-button:hover, QTimeEdit::down-button:hover, QDateEdit::down-button:hover, QDateTimeEdit::down-button:hover {\n"
"    color: #FFFFFF;\n"
"    border-bottom-right-radius: 5px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #84afe5, stop:1 #1168e4);\n"
"}\n"
"QSpinBox::up-arrow, QDoubleSpinBox::up-arrow, QTimeEdit::up-arrow, QDateEdit::up-arrow, QDateTimeEdit::up-arrow {\n"
"    image: url(/usr/share/icons/Adwaita/16x16/actions/go-up-symbolic.symbolic.png);\n"
"}\n"
"QSpinBox::down-arrow, QDoubleSpinBox::down-arrow, QTimeEdit::down-arrow, QDateEdit::down-arrow, QDateTimeEdit::down-arrow {\n"
"    image: url(/usr/share/icons/Adwaita/16x16/actions/go-down-symbolic.symbolic.png);\n"
"}\n"
"QProgressBar {\n"
"    max-height: 8px;\n"
"    text-align: center;\n"
"    font: italic bold 11px;\n"
"    color: #3d3d3d;\n"
"    border: 1px solid transparent;\n"
"    border-radius:4px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #ddd5d5, stop:0.5 #dad3d3, stop:1 #ddd5d5);\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #467dd1, stop:0.5 #3b88fc, stop:1 #467dd1);\n"
"    border-radius: 4px;\n"
"}\n"
"QProgressBar:disabled {\n"
"    color: #616161;\n"
"}\n"
"QProgressBar::chunk:disabled {\n"
"    background-color: #aeaeae;\n"
"}\n"
"QSlider::groove {\n"
"    border: 1px solid #bbbbbb;\n"
"    background-color: #52595d;\n"
"    border-radius: 4px;\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    height: 6px;\n"
"}\n"
"QSlider::groove:vertical {\n"
"    width: 6px;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    width: 12px;\n"
"    margin: -5px 0;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    height: 12px;\n"
"    margin: 0 -5px;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::add-page, QSlider::sub-page {\n"
"    border: 1px transparent;\n"
"    background-color: #52595d;\n"
"    border-radius: 4px;\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #ddd5d5, stop:0.5 #dad3d3, stop:1 #ddd5d5);\n"
"}\n"
"QSlider::sub-page:horizontal {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #467dd1, stop:0.5 #3b88fc, stop:1 #467dd1);\n"
"}\n"
"QSlider::add-page:vertical {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #467dd1, stop:0.5 #3b88fc, stop:1 #467dd1);\n"
"}\n"
"QSlider::sub-page:vertical {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ddd5d5, stop:0.5 #dad3d3, stop:1 #ddd5d5);\n"
"}\n"
"QSlider::add-page:horizontal:disabled, QSlider::sub-page:horizontal:disabled, QSlider::add-page:vertical:disabled, QSlider::sub-page:vertical:disabled {\n"
"    background: #b9b9b9;\n"
"}\n"
"QComboBox, QFontComboBox {\n"
"    border-width: 2px;\n"
"    border-radius: 8px;\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    background-color: #f4f4f4;\n"
"    color: #272727;\n"
"    padding-left: 5px;\n"
"}\n"
"QComboBox:editable, QComboBox:!editable, QComboBox::drop-down:editable, QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: #ffff;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    color: #272727;\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: url(/usr/share/icons/Adwaita/16x16/actions/go-down-symbolic.symbolic.png); /*Adawaita icon thene*/\n"
"}\n"
"\n"
"QComboBox::down-arrow:on {\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid darkgray;\n"
"    border-radius: 8px;\n"
"    selection-background-color: #dadada;\n"
"    selection-color: #272727;\n"
"    color: #272727;\n"
"    background: white;\n"
"}\n"
"QLabel, QCheckBox, QRadioButton {\n"
"    color: #272727;\n"
"}\n"
"QCheckBox {\n"
"    padding: 2px;\n"
"}\n"
"QCheckBox:disabled, QRadioButton:disabled {\n"
"    color: #808086;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QCheckBox:hover {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    padding-left: 1px;\n"
"    padding-right: 1px;\n"
"    padding-bottom: 1px;\n"
"    padding-top: 1px;\n"
"    border-width:1px;\n"
"    border-color: transparent;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    image: url(/usr/share/icons/Adwaita/16x16/actions/object-select-symbolic.symbolic.png);\n"
"    height: 15px;\n"
"    width: 15px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: #48a5fd;\n"
"    color: #ffffff;\n"
"    border-radius: 3px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #48a5fd, stop:0.5 #329cfb, stop:1 #48a5fd);\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    \n"
"    height: 15px;\n"
"    width: 15px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: #48a5fd;\n"
"    border-radius: 3px;\n"
"    background-color: #fbfdfa;\n"
"}\n"
"QLCDNumber {\n"
"    color: #616161;;\n"
"}\n"
"QMenuBar {\n"
"    background-color: #ececec;\n"
"}\n"
"QMenuBar::item {\n"
"    color: #616161;\n"
"    spacing: 3px;\n"
"    padding: 1px 4px;\n"
"    background-color: #ececec;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #dadada;\n"
"    color: #3d3d3d;\n"
"}\n"
"QMenu {\n"
"    background-color: #ececec;\n"
"}\n"
"QMenu::item:selected {\n"
"    background-color: #dadada;\n"
"    color: #3d3d3d;\n"
"}\n"
"QMenu::item {\n"
"    color: #616161;;\n"
"    background-color: #e0e0e0;\n"
"}\n"
"QTabWidget {\n"
"    color:rgb(0,0,0);\n"
"    background-color:#000000;\n"
"}\n"
"QTabWidget::pane {\n"
"    border-color: #050a0e;\n"
"    background-color: #e0e0e0;\n"
"    border-width: 1px;\n"
"    border-radius: 4px;\n"
"    position: absolute;\n"
"    top: -0.5em;\n"
"    padding-top: 0.5em;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    alignment: center;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    border-bottom: 1px solid #c0c0c0;\n"
"    padding: 3px;\n"
"    color: #272727;\n"
"    background-color: #fefefc;\n"
"    margin-left:0px;\n"
"}\n"
"QTabBar::tab:!last {\n"
"    border-right: 1px solid;\n"
"    border-right-color: #c0c0c0;\n"
"    border-bottom-color: #c0c0c0;\n"
"}\n"
"QTabBar::tab:first {\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"}\n"
"QTabBar::tab:last {\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:last:selected, QTabBar::tab:hover {\n"
"    color: #FFFFFF;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #84afe5, stop:1 #1168e4);\n"
"}\n"
"QRadioButton::indicator {\n"
"    height: 14px;\n"
"    width: 14px;\n"
"    border-style:solid;\n"
"    border-radius:7px;\n"
"    border-width: 1px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    border-color: #48a5fd;\n"
"    background-color: qradialgradient(cx:0.5, cy:0.5, radius:0.4,fx:0.5, fy:0.5, stop:0 #ffffff, stop:0.5 #ffffff, stop:0.6 #48a5fd, stop:1 #48a5fd);\n"
"}\n"
"QRadioButton::indicator:!checked {\n"
"    border-color: #a9b7c6;\n"
"    background-color: #fbfdfa;\n"
"}\n"
"QStatusBar {\n"
"    color:#027f7f;\n"
"}\n"
"\n"
"QDial {\n"
"    background: #16a085;\n"
"}\n"
"\n"
"QToolBox {\n"
"    color: #a9b7c6;\n"
"    background-color: #222b2e;\n"
"}\n"
"QToolBox::tab {\n"
"    color: #a9b7c6;\n"
"    background-color:#222b2e;\n"
"}\n"
"QToolBox::tab:selected {\n"
"    color: #FFFFFF;\n"
"    background-color:#222b2e;\n"
"}\n"
"QScrollArea {\n"
"    color: #FFFFFF;\n"
"    background-color:#222b2e;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    max-height: 10px;\n"
"    border: 1px transparent grey;\n"
"    margin: 0px 20px 0px 20px;\n"
"    background: transparent;\n"
"}\n"
"QScrollBar:vertical {\n"
"    max-width: 10px;\n"
"    border: 1px transparent grey;\n"
"    margin: 20px 0px 20px 0px;\n"
"    background: transparent;\n"
"}\n"
"QScrollBar::handle:vertical, QScrollBar::handle:horizontal {\n"
"    background: #52595d;\n"
"    border-style: transparent;\n"
"    border-radius: 4px;\n"
"    min-height: 25px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover, QScrollBar::handle:vertical:hover {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #467dd1, stop:0.5 #3b88fc, stop:1 #467dd1);\n"
"}\n"
"QScrollBar::add-line, QScrollBar::sub-line {\n"
"    border: 2px transparent grey;\n"
"    border-radius: 4px;\n"
"    subcontrol-origin: margin;\n"
"    background: #b9b9b9;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    width: 20px;\n"
"    subcontrol-position: right;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    height: 20px;\n"
"    subcontrol-position: bottom;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    width: 20px;\n"
"    subcontrol-position: left;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 20px;\n"
"    subcontrol-position: top;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed, QScrollBar::add-line:horizontal:pressed, QScrollBar::sub-line:horizontal:pressed, QScrollBar::sub-line:vertical:pressed {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #467dd1, stop:0.5 #3b88fc, stop:1 #467dd1);\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal, QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::up-arrow:vertical {\n"
"    image: url(/usr/share/icons/Adwaita/16x16/actions/go-up-symbolic.symbolic.png);\n"
"}\n"
"QScrollBar::down-arrow:vertical {\n"
"    image: url(/usr/share/icons/Adwaita/16x16/actions/go-down-symbolic.symbolic.png);\n"
"}\n"
"QScrollBar::left-arrow:horizontal {\n"
"    image: url(/usr/share/icons/Adwaita/16x16/actions/go-previous-symbolic.symbolic.png);\n"
"}\n"
"QScrollBar::right-arrow:horizontal {\n"
"    image: url(/usr/share/icons/Adwaita/16x16/actions/go-next-symbolic.symbolic.png);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stokGuncelleBtn = QtWidgets.QPushButton(self.centralwidget)
        self.stokGuncelleBtn.setGeometry(QtCore.QRect(1020, 560, 291, 101))
        self.stokGuncelleBtn.setObjectName("stokGuncelleBtn")
        self.tarih = QtWidgets.QCalendarWidget(self.centralwidget)
        self.tarih.setGeometry(QtCore.QRect(260, 100, 461, 271))
        self.tarih.setObjectName("tarih")
        self.stokSilBtn = QtWidgets.QPushButton(self.centralwidget)
        self.stokSilBtn.setGeometry(QtCore.QRect(670, 560, 291, 101))
        self.stokSilBtn.setObjectName("stokSilBtn")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(750, 70, 951, 341))
        self.tableWidget.setAutoScrollMargin(16)
        self.tableWidget.setRowCount(250)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(91)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.stokEkleBtn = QtWidgets.QPushButton(self.centralwidget)
        self.stokEkleBtn.setGeometry(QtCore.QRect(330, 560, 291, 101))
        self.stokEkleBtn.setObjectName("stokEkleBtn")
        self.cikis = QtWidgets.QPushButton(self.centralwidget)
        self.cikis.setGeometry(QtCore.QRect(1400, 870, 181, 71))
        self.cikis.setObjectName("cikis")
        self.arama_btn = QtWidgets.QPushButton(self.centralwidget)
        self.arama_btn.setGeometry(QtCore.QRect(1020, 700, 211, 71))
        self.arama_btn.setObjectName("arama_btn")
        self.arama_line = QtWidgets.QLineEdit(self.centralwidget)
        self.arama_line.setGeometry(QtCore.QRect(830, 720, 171, 41))
        self.arama_line.setAlignment(QtCore.Qt.AlignCenter)
        self.arama_line.setObjectName("arama_line")
        self.urun_tpl = QtWidgets.QLabel(self.centralwidget)
        self.urun_tpl.setGeometry(QtCore.QRect(580, 740, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.urun_tpl.setFont(font)
        self.urun_tpl.setText("")
        self.urun_tpl.setObjectName("urun_tpl")
        self.stok_lbl = QtWidgets.QLabel(self.centralwidget)
        self.stok_lbl.setGeometry(QtCore.QRect(250, 750, 331, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.stok_lbl.setFont(font)
        self.stok_lbl.setObjectName("stok_lbl")
        self.siparis_no = QtWidgets.QLineEdit(self.centralwidget)
        self.siparis_no.setGeometry(QtCore.QRect(450, 470, 181, 31))
        self.siparis_no.setToolTipDuration(1)
        self.siparis_no.setStatusTip("")
        self.siparis_no.setInputMask("")
        self.siparis_no.setText("")
        self.siparis_no.setMaxLength(10)
        self.siparis_no.setFrame(True)
        self.siparis_no.setAlignment(QtCore.Qt.AlignCenter)
        self.siparis_no.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.siparis_no.setClearButtonEnabled(True)
        self.siparis_no.setObjectName("siparis_no")
        self.renk = QtWidgets.QComboBox(self.centralwidget)
        self.renk.setGeometry(QtCore.QRect(760, 470, 111, 31))
        self.renk.setMaxVisibleItems(15)
        self.renk.setObjectName("renk")
        self.renk.addItem("")
        self.renk.addItem("")
        self.renk.addItem("")
        self.renk.addItem("")
        self.renk.addItem("")
        self.renk.addItem("")
        self.renk.addItem("")
        self.renk.addItem("")
        self.renk.addItem("")
        self.renk.addItem("")
        self.renk.addItem("")
        self.renk.addItem("")
        self.model = QtWidgets.QComboBox(self.centralwidget)
        self.model.setGeometry(QtCore.QRect(640, 470, 111, 31))
        self.model.setObjectName("model")
        self.model.addItem("")
        self.model.addItem("")
        self.model.addItem("")
        self.model.addItem("")
        self.model.addItem("")
        self.model.addItem("")
        self.model.addItem("")
        self.model.addItem("")
        self.model.addItem("")
        self.model.addItem("")
        self.model.addItem("")
        self.komisyon = QtWidgets.QComboBox(self.centralwidget)
        self.komisyon.setGeometry(QtCore.QRect(980, 470, 91, 31))
        self.komisyon.setObjectName("komisyon")
        self.komisyon.addItem("")
        self.komisyon.addItem("")
        self.komisyon.addItem("")
        self.komisyon.addItem("")
        self.komisyon.addItem("")
        self.komisyon.addItem("")
        self.komisyon.addItem("")
        self.komisyon.addItem("")
        self.komisyon.addItem("")
        self.komisyon.addItem("")
        self.komisyon.addItem("")
        self.beden = QtWidgets.QComboBox(self.centralwidget)
        self.beden.setGeometry(QtCore.QRect(880, 470, 91, 31))
        self.beden.setObjectName("beden")
        self.beden.addItem("")
        self.beden.addItem("")
        self.beden.addItem("")
        self.beden.addItem("")
        self.beden.addItem("")
        self.beden.addItem("")
        self.beden.addItem("")
        self.beden.addItem("")
        self.satis_fiyati = QtWidgets.QLineEdit(self.centralwidget)
        self.satis_fiyati.setGeometry(QtCore.QRect(1380, 470, 171, 31))
        self.satis_fiyati.setToolTipDuration(1)
        self.satis_fiyati.setStatusTip("")
        self.satis_fiyati.setInputMask("")
        self.satis_fiyati.setText("")
        self.satis_fiyati.setFrame(True)
        self.satis_fiyati.setAlignment(QtCore.Qt.AlignCenter)
        self.satis_fiyati.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.satis_fiyati.setClearButtonEnabled(True)
        self.satis_fiyati.setObjectName("satis_fiyati")
        self.muhasebe_gcs_btn = QtWidgets.QPushButton(self.centralwidget)
        self.muhasebe_gcs_btn.setGeometry(QtCore.QRect(1190, 870, 191, 71))
        self.muhasebe_gcs_btn.setObjectName("muhasebe_gcs_btn")
        self.kdv = QtWidgets.QComboBox(self.centralwidget)
        self.kdv.setGeometry(QtCore.QRect(1080, 470, 91, 31))
        self.kdv.setObjectName("kdv")
        self.kdv.addItem("")
        self.kdv.addItem("")
        self.kdv.addItem("")
        self.alis_fiyati = QtWidgets.QComboBox(self.centralwidget)
        self.alis_fiyati.setGeometry(QtCore.QRect(1180, 470, 91, 31))
        self.alis_fiyati.setObjectName("alis_fiyati")
        self.alis_fiyati.addItem("")
        self.alis_fiyati.addItem("")
        self.alis_fiyati.addItem("")
        self.alis_fiyati.addItem("")
        self.alis_fiyati.addItem("")
        self.alis_fiyati.addItem("")
        self.alis_fiyati.addItem("")
        self.alis_fiyati.addItem("")
        self.alis_fiyati.addItem("")
        self.alis_fiyati.addItem("")
        self.alis_fiyati.addItem("")
        self.alis_fiyati.addItem("")
        self.alis_fiyati.addItem("")
        self.alis_fiyati.addItem("")
        self.alis_fiyati.addItem("")
        self.alis_fiyati.addItem("")
        self.alis_fiyati.addItem("")
        self.alis_fiyati.addItem("")
        self.alis_fiyati.addItem("")
        self.alis_fiyati.addItem("")
        self.alis_fiyati.addItem("")
        self.alis_fiyati.addItem("")
        self.alis_fiyati.addItem("")
        self.alis_fiyati.addItem("")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(680, 440, 721, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.kargo = QtWidgets.QComboBox(self.centralwidget)
        self.kargo.setGeometry(QtCore.QRect(1280, 470, 91, 31))
        self.kargo.setObjectName("kargo")
        self.kargo.addItem("")
        self.kargo.addItem("")
        self.kargo.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(520, 440, 61, 29))
        self.label.setObjectName("label")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(1440, 440, 71, 29))
        self.label_9.setObjectName("label_9")
        self.ciro_lbl = QtWidgets.QLabel(self.centralwidget)
        self.ciro_lbl.setGeometry(QtCore.QRect(410, 810, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ciro_lbl.setFont(font)
        self.ciro_lbl.setObjectName("ciro_lbl")
        self.kar_lbl = QtWidgets.QLabel(self.centralwidget)
        self.kar_lbl.setGeometry(QtCore.QRect(410, 860, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.kar_lbl.setFont(font)
        self.kar_lbl.setObjectName("kar_lbl")
        self.ciro_label = QtWidgets.QLabel(self.centralwidget)
        self.ciro_label.setGeometry(QtCore.QRect(480, 800, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ciro_label.setFont(font)
        self.ciro_label.setText("")
        self.ciro_label.setObjectName("ciro_label")
        self.kar_label = QtWidgets.QLabel(self.centralwidget)
        self.kar_label.setGeometry(QtCore.QRect(480, 850, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.kar_label.setFont(font)
        self.kar_label.setText("")
        self.kar_label.setObjectName("kar_label")
        self.iade_btn = QtWidgets.QPushButton(self.centralwidget)
        self.iade_btn.setGeometry(QtCore.QRect(1360, 560, 291, 101))
        self.iade_btn.setObjectName("iade_btn")
        self.iade_line = QtWidgets.QComboBox(self.centralwidget)
        self.iade_line.setGeometry(QtCore.QRect(1570, 470, 91, 31))
        self.iade_line.setObjectName("iade_line")
        self.iade_line.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1884, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.stokGuncelleBtn.setText(_translate("MainWindow", "LİSTEYİ GÜNCELLE"))
        self.stokSilBtn.setText(_translate("MainWindow", "SİPARİŞ SİL"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "SİPARİŞ NO"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "MODEL"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "RENK"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "BEDEN"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "KOMİSYON"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "ALIŞ FİYATI"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "KARGO"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "SATIŞ FİYATI"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "KÂR"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "TARİH"))
        self.stokEkleBtn.setText(_translate("MainWindow", "SİPARİŞ EKLE"))
        self.cikis.setText(_translate("MainWindow", "ÇIKIŞ"))
        self.arama_btn.setText(_translate("MainWindow", "SİPARİŞ NO İLE ÜRÜN ARA"))
        self.arama_line.setPlaceholderText(_translate("MainWindow", "SİPARİŞ NO GİRİNİZ"))
        self.stok_lbl.setText(_translate("MainWindow", "SATILAN TOPLAM ÜRÜN SAYISI:"))
        self.siparis_no.setToolTip(_translate("MainWindow", "SATIŞ FİYATI"))
        self.siparis_no.setPlaceholderText(_translate("MainWindow", "SİPARİŞ NO"))
        self.renk.setItemText(0, _translate("MainWindow", "SİYAH"))
        self.renk.setItemText(1, _translate("MainWindow", "KIRMIZI"))
        self.renk.setItemText(2, _translate("MainWindow", "BEYAZ"))
        self.renk.setItemText(3, _translate("MainWindow", "YEŞİL"))
        self.renk.setItemText(4, _translate("MainWindow", "PEMBE"))
        self.renk.setItemText(5, _translate("MainWindow", "KAHVERENGİ"))
        self.renk.setItemText(6, _translate("MainWindow", "MOR"))
        self.renk.setItemText(7, _translate("MainWindow", "LACİVERT"))
        self.renk.setItemText(8, _translate("MainWindow", "BORDO"))
        self.renk.setItemText(9, _translate("MainWindow", "BEJ"))
        self.renk.setItemText(10, _translate("MainWindow", "TURUNCU"))
        self.renk.setItemText(11, _translate("MainWindow", "İADE"))
        self.model.setItemText(0, _translate("MainWindow", "DÜĞMELİ"))
        self.model.setItemText(1, _translate("MainWindow", "LASTİKLİ"))
        self.model.setItemText(2, _translate("MainWindow", "KEMERLİ"))
        self.model.setItemText(3, _translate("MainWindow", "KUŞAKLI"))
        self.model.setItemText(4, _translate("MainWindow", "TUNİK"))
        self.model.setItemText(5, _translate("MainWindow", "KISA TUNİK"))
        self.model.setItemText(6, _translate("MainWindow", "TULUM"))
        self.model.setItemText(7, _translate("MainWindow", "SK - RJ"))
        self.model.setItemText(8, _translate("MainWindow", "SK - RM"))
        self.model.setItemText(9, _translate("MainWindow", " S - RM"))
        self.model.setItemText(10, _translate("MainWindow", "GİDER"))
        self.komisyon.setItemText(0, _translate("MainWindow", "10"))
        self.komisyon.setItemText(1, _translate("MainWindow", "12"))
        self.komisyon.setItemText(2, _translate("MainWindow", "14"))
        self.komisyon.setItemText(3, _translate("MainWindow", "15"))
        self.komisyon.setItemText(4, _translate("MainWindow", "16"))
        self.komisyon.setItemText(5, _translate("MainWindow", "18"))
        self.komisyon.setItemText(6, _translate("MainWindow", "20"))
        self.komisyon.setItemText(7, _translate("MainWindow", "22"))
        self.komisyon.setItemText(8, _translate("MainWindow", "25"))
        self.komisyon.setItemText(9, _translate("MainWindow", "1"))
        self.komisyon.setItemText(10, _translate("MainWindow", "1111111111"))
        self.beden.setItemText(0, _translate("MainWindow", "36"))
        self.beden.setItemText(1, _translate("MainWindow", "38"))
        self.beden.setItemText(2, _translate("MainWindow", "40"))
        self.beden.setItemText(3, _translate("MainWindow", "42"))
        self.beden.setItemText(4, _translate("MainWindow", "44"))
        self.beden.setItemText(5, _translate("MainWindow", "46"))
        self.beden.setItemText(6, _translate("MainWindow", "48"))
        self.beden.setItemText(7, _translate("MainWindow", "STANDART"))
        self.satis_fiyati.setToolTip(_translate("MainWindow", "SATIŞ FİYATI"))
        self.satis_fiyati.setPlaceholderText(_translate("MainWindow", "SATIŞ FİYATI(TL)"))
        self.muhasebe_gcs_btn.setText(_translate("MainWindow", "MUHASEBE"))
        self.kdv.setItemText(0, _translate("MainWindow", "8"))
        self.kdv.setItemText(1, _translate("MainWindow", "1"))
        self.kdv.setItemText(2, _translate("MainWindow", "18"))
        self.alis_fiyati.setItemText(0, _translate("MainWindow", "50"))
        self.alis_fiyati.setItemText(1, _translate("MainWindow", "75"))
        self.alis_fiyati.setItemText(2, _translate("MainWindow", "80"))
        self.alis_fiyati.setItemText(3, _translate("MainWindow", "85"))
        self.alis_fiyati.setItemText(4, _translate("MainWindow", "90"))
        self.alis_fiyati.setItemText(5, _translate("MainWindow", "95"))
        self.alis_fiyati.setItemText(6, _translate("MainWindow", "100"))
        self.alis_fiyati.setItemText(7, _translate("MainWindow", "110"))
        self.alis_fiyati.setItemText(8, _translate("MainWindow", "120"))
        self.alis_fiyati.setItemText(9, _translate("MainWindow", "125"))
        self.alis_fiyati.setItemText(10, _translate("MainWindow", "130"))
        self.alis_fiyati.setItemText(11, _translate("MainWindow", "140"))
        self.alis_fiyati.setItemText(12, _translate("MainWindow", "150"))
        self.alis_fiyati.setItemText(13, _translate("MainWindow", "190"))
        self.alis_fiyati.setItemText(14, _translate("MainWindow", "200"))
        self.alis_fiyati.setItemText(15, _translate("MainWindow", "250"))
        self.alis_fiyati.setItemText(16, _translate("MainWindow", "500"))
        self.alis_fiyati.setItemText(17, _translate("MainWindow", "750"))
        self.alis_fiyati.setItemText(18, _translate("MainWindow", "1000"))
        self.alis_fiyati.setItemText(19, _translate("MainWindow", "1500"))
        self.alis_fiyati.setItemText(20, _translate("MainWindow", "1750"))
        self.alis_fiyati.setItemText(21, _translate("MainWindow", "1800"))
        self.alis_fiyati.setItemText(22, _translate("MainWindow", "2000"))
        self.alis_fiyati.setItemText(23, _translate("MainWindow", "1"))
        self.label_3.setText(_translate("MainWindow", "MODEL"))
        self.label_4.setText(_translate("MainWindow", "RENK"))
        self.label_5.setText(_translate("MainWindow", "BEDEN"))
        self.label_6.setText(_translate("MainWindow", "KOMİSYON"))
        self.label_7.setText(_translate("MainWindow", "KDV"))
        self.label_8.setText(_translate("MainWindow", "ALIŞ FİYATI"))
        self.label_10.setText(_translate("MainWindow", "KARGO"))
        self.kargo.setItemText(0, _translate("MainWindow", "23"))
        self.kargo.setItemText(1, _translate("MainWindow", "45"))
        self.kargo.setItemText(2, _translate("MainWindow", "1"))
        self.label.setText(_translate("MainWindow", "SİPARİŞ NO"))
        self.label_9.setText(_translate("MainWindow", "SATIŞ FİYATI"))
        self.ciro_lbl.setText(_translate("MainWindow", "CİRO:"))
        self.kar_lbl.setText(_translate("MainWindow", "KAR:"))
        self.iade_btn.setText(_translate("MainWindow", "İADE DÜŞ"))
        self.iade_line.setItemText(0, _translate("MainWindow", "-40"))
